In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("Temporary_data3_Left_Right_Copy.xlsx")

In [3]:
X = data.drop(columns="CDRGLOB")
y = data["CDRGLOB"]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.25, random_state=42)

In [14]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [ ]:

#svc = SVC(random_state=0)

#param_grid = {
              #'kernel': ["linear", "rbf"],
              #'gamma': ["scale", "auto"]
              #}

#grid = GridSearchCV(estimator=svc, param_grid=param_grid)

In [ ]:
#grid.fit(X_train, y_train);

In [ ]:
#my_params = grid.best_params_
#my_params

{'gamma': 'scale', 'kernel': 'linear'}

In [6]:
my_C = np.linspace(0.5,20, num=4)

In [7]:
svc = SVC(random_state=0, kernel ="linear", gamma="scale")

param_grid = {'C': my_C,
              }
grid = GridSearchCV(estimator=svc, param_grid=param_grid)

In [8]:
grid.fit(X_train, y_train);

In [11]:
grid.best_params_

{'C': 7.0}

In [15]:
svc = SVC(random_state=0, kernel ="linear", gamma="scale", C = 7.0)
my_predictions_SVC = svc.fit(X_train,y_train).predict(X_test)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix
target_names = ['CDRGLOB 0', 'CDRGLOB 1', 'CDRGLOB 2', 'CDRGLOB 3']

In [17]:
cr_svc = classification_report(y_test, my_predictions_SVC, target_names=target_names)
print(cr_svc)

              precision    recall  f1-score   support

   CDRGLOB 0       0.86      0.78      0.82       184
   CDRGLOB 1       0.58      0.67      0.62       108
   CDRGLOB 2       0.47      0.41      0.44        39
   CDRGLOB 3       0.23      0.38      0.29         8

    accuracy                           0.69       339
   macro avg       0.53      0.56      0.54       339
weighted avg       0.71      0.69      0.70       339



In [18]:
conf_svc = confusion_matrix(y_test, my_predictions_SVC)
print(conf_svc)

[[144  40   0   0]
 [ 21  72  14   1]
 [  2  12  16   9]
 [  0   1   4   3]]


In [19]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(random_state=0)

In [20]:
param_grid_dtc = {'criterion': ["gini", "entropy"],
              'max_features': ["auto", "log2", None],
              'class_weight': ["balanced",None],
              'splitter': ["best", "random"]
              }

grid_dtc = GridSearchCV(estimator=dtc, param_grid=param_grid_dtc)

In [21]:
grid_dtc.fit(X_train, y_train);

In [22]:
grid_dtc.best_params_

{'class_weight': None,
 'criterion': 'entropy',
 'max_features': None,
 'splitter': 'best'}

In [23]:
DTC = grid_dtc.best_estimator_
my_predictions_DTC = DTC.fit(X_train,y_train).predict(X_test)

In [24]:
cr_dtc = classification_report(y_test, my_predictions_DTC, target_names=target_names)
print(cr_dtc)

              precision    recall  f1-score   support

   CDRGLOB 0       0.84      0.76      0.79       184
   CDRGLOB 1       0.49      0.54      0.51       108
   CDRGLOB 2       0.41      0.46      0.43        39
   CDRGLOB 3       0.36      0.50      0.42         8

    accuracy                           0.65       339
   macro avg       0.53      0.56      0.54       339
weighted avg       0.67      0.65      0.65       339



In [25]:
conf_dtc = confusion_matrix(y_test, my_predictions_DTC)
conf_dtc

array([[139,  44,   1,   0],
       [ 26,  58,  22,   2],
       [  1,  15,  18,   5],
       [  0,   1,   3,   4]])

In [26]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)

In [27]:
param_grid_rfc = {'criterion': ["gini", "entropy", "log_loss"],
              'max_features': ["sqrt", "log2", None],
              'class_weight': ["balanced",None],
              'oob_score': [True, False]
              }
grid_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid_rfc)

In [28]:
grid_rfc.fit(X_train, y_train);

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py", line 467, in fit
    for i, t in enumerate(trees)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.7/dist-packages/joblib/par

In [29]:
grid_rfc.best_params_

{'class_weight': 'balanced',
 'criterion': 'entropy',
 'max_features': None,
 'oob_score': True}

In [30]:
RFC = grid_rfc.best_estimator_
my_predictions_RFC = RFC.fit(X_train,y_train).predict(X_test)

In [33]:
cr_rfc = classification_report(y_test, my_predictions_RFC, target_names=target_names)
print("Random Forest Report")
print(cr_rfc)

print("Decision Tree Report")
print(cr_dtc)

print("Support Vector Machine Report")
print(cr_svc)

Random Forest Report
              precision    recall  f1-score   support

   CDRGLOB 0       0.87      0.85      0.86       184
   CDRGLOB 1       0.63      0.73      0.68       108
   CDRGLOB 2       0.56      0.38      0.45        39
   CDRGLOB 3       0.38      0.38      0.38         8

    accuracy                           0.75       339
   macro avg       0.61      0.58      0.59       339
weighted avg       0.75      0.75      0.74       339

Decision Tree Report
              precision    recall  f1-score   support

   CDRGLOB 0       0.84      0.76      0.79       184
   CDRGLOB 1       0.49      0.54      0.51       108
   CDRGLOB 2       0.41      0.46      0.43        39
   CDRGLOB 3       0.36      0.50      0.42         8

    accuracy                           0.65       339
   macro avg       0.53      0.56      0.54       339
weighted avg       0.67      0.65      0.65       339

Support Vector Machine Report
              precision    recall  f1-score   support

   

In [34]:
conf_rfc = confusion_matrix(y_test, my_predictions_RFC)
print("Random Forest Confusion Matrix")
print(conf_rfc)

print("Decision Tree Confusion Matrix")
print(conf_dtc)

print("Support Vector Machine Confusion Matrix")
print(conf_svc)

Random Forest Confusion Matrix
[[156  28   0   0]
 [ 22  79   7   0]
 [  1  18  15   5]
 [  0   0   5   3]]
Decision Tree Confusion Matrix
[[139  44   1   0]
 [ 26  58  22   2]
 [  1  15  18   5]
 [  0   1   3   4]]
Support Vector Machine Confusion Matrix
[[144  40   0   0]
 [ 21  72  14   1]
 [  2  12  16   9]
 [  0   1   4   3]]


Decision  Tree algoritması CDRGLOB=3 için diğerlerinden daha iyi sonuç çıkarsa da ilgili sınıfa ait veri sayısı oldukça az olduğu için diğerlerinin bu noktada daha düşük çıkması gayet olasıdır. Veri sayısının çok olduğu CDRGLOB 0 ve 1 için ise random forest algoritmasının farkı oldukça vardır. Genele bakarsak random forest en iyi sonuçları çıkarmıştır.