TASK-7A: Please apply one-hot encoding method on one of the categorical variables (not SEX/gender) for the given AD dataset. Please explain what kind of transformation occured on the dataset. 

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_excel("Temporary_data3_Left_Right_Copy.xlsx")
data.iloc[:,20:40].head()

DEPD  ANX  ELAT  APA  DISN  IRR  MOT  NITE  APP  NACCGDS  DROPACT  \
0     1    0     0    0     0    0    0     0    0        0        0   
1     0    0     0    0     0    1    0     0    0        0        0   
2     0    0     0    0     0    0    0     0    0        2        1   
3     0    0     0    0     0    0    0     0    0        0        0   
4     0    0     0    0     0    0    0     0    0        1        0   

   NACCMMSE  NACCAGEB  NACCAMD  NACCBMI  NACCAPOE  NACCNE4S   NACCICV  \
0        30        56       10     25.1         3         0  1399.056   
1        19        65        6     30.3         1         0  1578.180   
2        29        58        1     23.2         1         0  1455.550   
3        30        72        3     30.4         1         0  1494.650   
4        27        82        9     20.8         1         0  1494.067   

   NACCBRNV  NACCWMVL  
0  1118.929   481.802  
1  1107.680   477.910  
2  1187.760   527.470  
3  1115.330   478.960  
4  1014.743   444.578

In [ ]:
any((data.eq('exact_string')).any())

False

In [ ]:
data["NACCAPOE"].unique()

# NACCAPOE means APOE genotype.

array([3, 1, 2, 4, 6, 5])

In [ ]:

a = pd.get_dummies(data["NACCAPOE"])
a



1  2  3  4  5  6
0     0  0  1  0  0  0
1     1  0  0  0  0  0
2     1  0  0  0  0  0
3     1  0  0  0  0  0
4     1  0  0  0  0  0
...  .. .. .. .. .. ..
1349  1  0  0  0  0  0
1350  1  0  0  0  0  0
1351  1  0  0  0  0  0
1352  1  0  0  0  0  0
1353  0  0  0  1  0  0

[1354 rows x 6 columns]

In [ ]:
data = data.drop("NACCAPOE",axis=1)

In [ ]:
labels = ["NACCAPOE-1","NACCAPOE-2","NACCAPOE-3","NACCAPOE-4","NACCAPOE-5","NACCAPOE-6"]

for label,i in zip(labels,range(6)):
  data[f"{label}"] = a.iloc[:,i]

data.iloc[:,-6:]

NACCAPOE-1  NACCAPOE-2  NACCAPOE-3  NACCAPOE-4  NACCAPOE-5  NACCAPOE-6
0              0           0           1           0           0           0
1              1           0           0           0           0           0
2              1           0           0           0           0           0
3              1           0           0           0           0           0
4              1           0           0           0           0           0
...          ...         ...         ...         ...         ...         ...
1349           1           0           0           0           0           0
1350           1           0           0           0           0           0
1351           1           0           0           0           0           0
1352           1           0           0           0           0           0
1353           0           0           0           1           0           0

[1354 rows x 6 columns]

TASK-7B: Please provide a couple of pivot tables in order to illustrate how SEX variable is influential on our target array (CDRGLOB). Please provide a few multidimensional analyses (not limited to two variables).

In [ ]:
data.pivot_table("CDRGLOB", index=['SEX',"DIABETES"], columns="ALCOHOL")

ALCOHOL              0         1         2
SEX DIABETES                              
1   0         0.858140  1.285714  1.074074
    1         0.861702  2.000000  1.090909
    2         1.000000       NaN  0.000000
2   0         0.590764  0.714286  0.400000
    1         0.581818       NaN  1.000000
    2         0.625000       NaN       NaN

In [ ]:
data.pivot_table("CDRGLOB", index=['SEX',"HXHYPER"], columns="HYPERCHO")

HYPERCHO            0         1         2
SEX HXHYPER                              
1   0        0.743590  0.801980  0.666667
    1        0.957447  0.922764  1.900000
2   0        0.436620  0.492537  0.545455
    1        0.656250  0.719557  0.650000

TASK-7C: Referring to the problem in part B, please provide a potential solution to the gender-based issue that appears as a bottleneck for the model development phase. One possible solution might be to provide normalization of the numeric columns with respect to the total brain volume (NACCBRNV column).

In [ ]:
data.iloc[:,37:-6] = data.iloc[:,37:-6].div(data.NACCBRNV,axis=0)
data.iloc[:,37:-6].head()


NACCBRNV  NACCWMVL    CSFVOL   GRAYVOL  WHITEVOL    WMHVOL   CEREALL  \
0       1.0  0.430592  0.249987  0.569773  0.430227  0.000365  1.062829   
1       1.0  0.431451  0.423173  0.570138  0.429862  0.001589  1.248402   
2       1.0  0.444088  0.224296  0.557074  0.442926  0.001162  1.049901   
3       1.0  0.429433  0.337873  0.572790  0.427210  0.002224  1.118978   
4       1.0  0.438119  0.464283  0.569958  0.430042  0.008077  1.262842   

   CERETISS   CERECSF    CEREGR  ...    RSUPFR   RSUPFRM   RSUPPAR  RSUPPARM  \
0  0.851212  0.211614  0.462603  ...  0.024938  0.001980  0.009248  0.001521   
1  0.880778  0.367624  0.481710  ...  0.026235  0.002428  0.008351  0.001472   
2  0.871725  0.178176  0.464681  ...  0.027783  0.002138  0.011526  0.001313   
3  0.865950  0.253028  0.480504  ...  0.028404  0.002161  0.008643  0.001300   
4  0.872748  0.390093  0.479283  ...  0.027655  0.001922  0.008980  0.001028   

    RSUPTEM  RSUPTEMM   RSUPMAR  RSUPMARM    RTRTEM   RTRTEMM  
0  0.011998  0.001557  0.008821  0.001501  0.000796  0.001068  
1  0.013433  0.002076  0.006563  0.001706  0.001246  0.001833  
2  0.013664  0.001743  0.008512  0.001549  0.000850  0.001263  
3  0.013548  0.001470  0.009316  0.001641  0.000663  0.000986  
4  0.013182  0.001603  0.007474  0.001438  0.000654  0.000840  

[5 rows x 148 columns]

TASK-7D: After the normalization process, please provide a correlation matrix to report the critical features that have high correlation (positive or negative) with the target array (CDRGLOB).

In [ ]:
mask = (data.corr()>0.30) | (data.corr()<-0.30)
data.corr()[mask][16:17].dropna(1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only
  


INDEPEND  CDRGLOB       DEL      AGIT       ANX       APA      DISN  \
CDRGLOB  0.693881      1.0  0.300995  0.373153  0.319968  0.448558  0.326447   

              IRR       MOT  NACCMMSE  ...   CEREALL   CERECSF    LHIPPO  \
CDRGLOB  0.319788  0.330414  -0.74666  ...  0.367395  0.420518 -0.390896   

           RHIPPO  LLATVENT  RLATVENT  THIRVENT  LTEMPCOR     LENTM   RENTM  
CDRGLOB -0.372265  0.443272  0.435256   0.38337 -0.305253 -0.366255 -0.3858  

[1 rows x 21 columns]

TASK-7E: Please develop 3 distinct formulas (in other words derived features like BMI score) that involve the critical features in Part-7D and then ensure that these derived features could be used as predictive variables for CDRGLOB (again correlation analysis will give you insight).

In [ ]:
data['NEW-1'] = (data['DEL']+data['AGIT']+data['IRR'])/3
data['NEW-2'] = (data['CSFVOL']*data['CEREALL']*data['CERECSF'])
data['NEW-3'] = (data['LLATVENT']*data['RLATVENT'])/(data['LHIPPO']*data['RHIPPO'])
data.iloc[:,-3:].head()

NEW-1     NEW-2       NEW-3
0  0.000000  0.056224    4.670298
1  0.666667  0.194212  168.185662
2  0.000000  0.041958    1.516090
3  0.000000  0.095663    8.205508
4  0.000000  0.228718  174.374884

In [ ]:
data[['NEW-1','NEW-2','NEW-3','CDRGLOB']].corr().iloc[-1:,:-1]

NEW-1     NEW-2     NEW-3
CDRGLOB  0.436518  0.393219  0.382166

TASK-7F: Then please develop a machine learning model with the 3 derived features that you obtain in 7E via the use of train-test split (be careful about stratify parameter in this function) and gridsearchCV function as well as a classification algorithm (such as Gaussian Naive Bayes) but please do not forget to optimize its hyperparameters. Finally, please report your findings via the use of classification report function (also a sklearn function). 


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,-3:], data["CDRGLOB"], test_size=0.20, random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
gnb = KNeighborsClassifier()
gnb.fit(X_train,y_train)
gnb_predict = gnb.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, gnb_predict)

0.5387453874538746

In [ ]:
my_n_neighbors = my_n_estimators = np.linspace(1,15,num=5,dtype="int")
print(my_n_neighbors)

my_weights=['uniform','distance']

my_algorithm = ["auto", "ball_tree", "kd_tree", "brute"]

my_leaf_size = np.linspace(10,50,num=5,dtype="int")
print(my_leaf_size)

my_p = np.linspace(1,5,num=5,dtype="int")
print(my_p)

[ 1  4  8 11 15]
[10 20 30 40 50]
[1 2 3 4 5]


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_neighbors': my_n_neighbors,
              'weights' : my_weights,
              'algorithm' : my_algorithm,
              'leaf_size' : my_leaf_size,
              'p' : my_p
              }

grid = GridSearchCV(estimator=gnb, param_grid=param_grid)

In [ ]:
grid.fit(X_train, y_train);

In [ ]:
grid.best_params_
#Accuracy changed inversely with var_smoothing value,

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 4,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
gnb = grid.best_estimator_
my_predictions = gnb.fit(X_train,y_train).predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
target_names = ["1","2","3","4"]
print(classification_report(y_test, my_predictions, target_names=target_names))

              precision    recall  f1-score   support

           1       0.61      0.84      0.71       128
           2       0.48      0.32      0.39       102
           3       0.23      0.16      0.19        32
           4       0.00      0.00      0.00         9

    accuracy                           0.54       271
   macro avg       0.33      0.33      0.32       271
weighted avg       0.50      0.54      0.50       271

