In [ ]:
import numpy as np

In [ ]:

x = np.zeros((8,6), dtype=int)
x

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
for j in range(8):
  for i in range(6):

    def checker(x,num):
      return (np.any(x[j] == num))

    num = np.random.randint(1,50)
    while checker(x,num) == True:
      num = np.random.randint(1,50)
      checker(x,num)
    x[j,i] = num

x

array([[45,  7,  1, 17, 47, 30],
       [ 3, 32,  2,  5, 38, 21],
       [30, 26, 31, 48,  9, 40],
       [32,  6, 19, 48, 16, 13],
       [42, 17, 43, 25, 24, 46],
       [13, 12, 17, 11, 28, 38],
       [11, 45, 26, 42, 15, 20],
       [44, 24,  7, 22, 27, 37]])

In [ ]:
x = np.transpose(x)
x

array([[45,  3, 30, 32, 42, 13, 11, 44],
       [ 7, 32, 26,  6, 17, 12, 45, 24],
       [ 1,  2, 31, 19, 43, 17, 26,  7],
       [17,  5, 48, 48, 25, 11, 42, 22],
       [47, 38,  9, 16, 24, 28, 15, 27],
       [30, 21, 40, 13, 46, 38, 20, 37]])